# Generated by Django 5.1.7 on 2025-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0002_lecturecompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturevideo",
            name="video_file",
            field=models.FileField(upload_to="lecture_videos/"),
        ),
    ]
