# Generated by Django 5.1.7 on 2025-04-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_user_coursetoken_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetoken",
            name="intro_video",
            field=models.FileField(default="", upload_to="intro_videos/"),
        ),
        migrations.AlterField(
            model_name="coursetoken",
            name="motivation",
            field=models.TextField(
                help_text="Write your motivation or plan for the course, including how you plan to organize it."
            ),
        ),
    ]
